-- Sistem pembagian tugas penyebaran undangan WJNC.
-- Data undangan (451 baris) di-seed langsung dari file Excel "DAFTAR UNDANGAN
-- WJNC" — lihat blok insert di bagian bawah file ini.

create table if not exists undangan (
  id uuid primary key default gen_random_uuid(),
  kategori text not null check (kategori in ('vvip', 'vip_opd_mitra', 'wilayah_ormas', 'lansia_disabilitas_anak')),
  sub_kelompok text,
  nomor int,
  nama text not null,
  lokasi_parkir text,
  status text not null default 'belum' check (status in ('belum', 'selesai', 'kendala')),
  pic_user_id uuid references profiles(id) on delete set null,
  catatan text,
  bukti_url text,
  diperbarui_oleh uuid references profiles(id) on delete set null,
  diperbarui_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_undangan_pic on undangan(pic_user_id);
create index if not exists idx_undangan_kategori on undangan(kategori);

-- Pegawai biasa (PIC) cuma boleh mengubah status/catatan/bukti_url baris
-- miliknya sendiri — bukan nama/kategori/penugasan (itu hak admin saja).
create or replace function proteksi_undangan() returns trigger
language plpgsql as $$
begin
  if not is_admin() then
    new.kategori := old.kategori;
    new.sub_kelompok := old.sub_kelompok;
    new.nomor := old.nomor;
    new.nama := old.nama;
    new.lokasi_parkir := old.lokasi_parkir;
    new.pic_user_id := old.pic_user_id;
  end if;
  new.diperbarui_oleh := auth.uid();
  new.diperbarui_at := now();
  return new;
end;
$$;

drop trigger if exists trg_proteksi_undangan on undangan;
create trigger trg_proteksi_undangan
  before update on undangan
  for each row execute function proteksi_undangan();

alter table undangan enable row level security;

-- Semua yang login boleh lihat (dipakai admin buat dashboard progres
-- keseluruhan). Insert/delete hanya admin. Update: admin bebas, pegawai
-- biasa hanya baris yang PIC-nya dia sendiri (dibatasi trigger di atas).
create policy undangan_select on undangan for select to authenticated using (true);
create policy undangan_insert_admin on undangan for insert to authenticated with check (is_admin());
create policy undangan_delete_admin on undangan for delete to authenticated using (is_admin());
create policy undangan_update on undangan for update to authenticated
  using (is_admin() or pic_user_id = auth.uid());

-- =========================================================
-- SEED DATA — 451 undangan dari file Excel WJNC
-- =========================================================

insert into undangan (kategori, sub_kelompok, nomor, nama, lokasi_parkir) values
('vvip', 'UNDANGAN KEMENTRIAN', 1, 'Menteri Pariwisata ( Widiyanti Putri Wardhana )', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN KEMENTRIAN', 2, 'Wakil Menteri Pariwisata ( Ni Luh Enik Ermawati )', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN KEMENTRIAN', 3, 'Menteri Ekonomi Kreatif ( Teuku Riefky Harsya )', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN KEMENTRIAN', 4, 'Menteri Kebudayaan ( Fadli Zon )', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN KEMENTRIAN', 5, 'Menteri Usaha Mikro Kecil dan Menengah ( Maman Abdurrahman )', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN KEMENTRIAN', 6, 'Utusan Khusus Presiden Bidang Pariwisata ( Zita Anjani )', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN KEMENTRIAN', 7, 'Direktur Badan Otorita Borobudur', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 8, 'Bapak Gubernur Daerah Istimewa Yogyakarta', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 9, 'Bapak Wakil Gubernur Daerah Istimewa Yogyakarta', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 10, 'Gusti Kanjeng Ratu Hemas', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 11, 'Gusti Kanjeng Bendara Raden Ayu Adipati Pakualam X', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 12, 'Bapak Wali Kota Yogyakarta', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 13, 'Ibu Wali Kota Yogyakarta sebagai Ketua TP PKK Kota Yogyakarta', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 14, 'Bapak Wakil Wali Kota Yogyakarta', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 15, 'Ibu Wakil Wali Kota Yogyakarta sebagai Wakil Ketua TP PKK Kota Yogyakarta', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 16, 'Bupati Kulonprogo', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 17, 'Bupati Sleman', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 18, 'Bupati Gunung Kidul', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 19, 'Bupati Bantul', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 20, 'Gusti Kanjeng Ratu Mangkubumi', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 21, 'Kanjeng Pangeran Haryo Wironegoro', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 22, 'Gusti Kanjeng Ratu Condrokirono', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 23, 'Gusti Kanjeng Ratu Maduretno', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 24, 'Kanjeng Pangeran Haryo Purbodiningrat', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 25, 'Gusti Kanjeng Ratu Hayu', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 26, 'Kanjeng Pangeran Haryo Notonegoro', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 27, 'Gusti Kanjeng Ratu Bendara', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 28, 'Kanjeng Pangeran Haryo Yudanegoro', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 29, 'Duta Besar Mongolia', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN UTAMA', 30, 'Duta Besar Cekoslovakia', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN ANGGOTA DPD DAN DPR RI DAPIL D.I.YOGYAKARTA', 31, 'Ir. Ahmad Syauqi Soeratno,M.M. ( DPD D.I.Yogyakarta )', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN ANGGOTA DPD DAN DPR RI DAPIL D.I.YOGYAKARTA', 32, 'R.A. Yasinta Sekar Wangi Mega ( DPD D.I.Yogyakarta )', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN ANGGOTA DPD DAN DPR RI DAPIL D.I.YOGYAKARTA', 33, 'Hilmi Muhammad ( DPD D.I.Yogyakarta )', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN ANGGOTA DPD DAN DPR RI DAPIL D.I.YOGYAKARTA', 34, 'MY Esti Wijayanti (Anggota DPR RI Dapil DIY )', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN ANGGOTA DPD DAN DPR RI DAPIL D.I.YOGYAKARTA', 35, 'Kaisar Abu Hanifah (Anggota DPR RI Dapil DIY)', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN ANGGOTA DPD DAN DPR RI DAPIL D.I.YOGYAKARTA', 36, 'Siti Hediati Soeharto,S.E (Anggota DPR RI Dapil DIY)', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN ANGGOTA DPD DAN DPR RI DAPIL D.I.YOGYAKARTA', 37, 'G.M. Totok Hedi Santosa (Anggota DPR RI Dapil DIY)', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN ANGGOTA DPD DAN DPR RI DAPIL D.I.YOGYAKARTA', 38, 'Dr. H.M. Gandung pardiman, M.M (Anggota DPR RI Dapil DIY)', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN ANGGOTA DPD DAN DPR RI DAPIL D.I.YOGYAKARTA', 39, 'H. Subardi, S.H.,M.H. (Anggota DPR RI Dapil DIY)', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN ANGGOTA DPD DAN DPR RI DAPIL D.I.YOGYAKARTA', 40, 'Dr. H. Sukamta  (Anggota DPR RI Dapil DIY)', 'Beteng Vredeburg'),
('vvip', 'UNDANGAN ANGGOTA DPD DAN DPR RI DAPIL D.I.YOGYAKARTA', 41, 'H. Totok Daryanto, S.E (Anggota DPR RI Dapil DIY)', 'Beteng Vredeburg'),
('vvip', 'FORKOMPIMDA DIY +', 42, 'Kapolda Daerah Istimewa Yogyakarta', 'Taman Budaya'),
('vvip', 'FORKOMPIMDA DIY +', 43, 'Ketua DPRD Daerah Istimewa Yogyakarta', 'Taman Budaya'),
('vvip', 'FORKOMPIMDA DIY +', 49, 'Komandan Korem 072/Pamungkas', 'Taman Budaya'),
('vvip', 'FORKOMPIMDA DIY +', 50, 'Kepala Kejaksaan Tinggi Daerah Istimewa Yogyakarta', 'Taman Budaya'),
('vvip', 'FORKOMPIMDA DIY +', 51, 'Ketua Pengadilan Tinggi Yogyakarta', 'Taman Budaya'),
('vvip', 'FORKOMPIMDA DIY +', 52, 'Danlanud Adisutjipto Yogyakarta', 'Taman Budaya'),
('vvip', 'FORKOMPIMDA DIY +', 53, 'Danlanal Yogyakarta', 'Taman Budaya'),
('vvip', 'FORKOMPIMDA DIY +', 54, 'Gubernur AAU Adisucipto', 'Taman Budaya'),
('vvip', 'FORKOMPIMDA DIY +', 55, 'Pimpinan Wilayah Bank Indonesia Yogyakarta', 'Taman Budaya'),
('vvip', 'FORKOMPIMDA  KOTA YK +', 56, 'Ketua DPRD Kota Yogyakarta (F. X. Wisnu Sabdono Putro, S.H.)', 'Taman Budaya'),
('vvip', 'FORKOMPIMDA  KOTA YK +', 57, 'Wakil Ketua DPRD Kota Yogyakarta (R. M. Sinarbiyatnujanat, S.E.)', 'Taman Budaya'),
('vvip', 'FORKOMPIMDA  KOTA YK +', 58, 'Wakil Ketua DPRD Kota Yogyakarta (Triyono Hari Kuncoro)', 'Taman Budaya'),
('vvip', 'FORKOMPIMDA  KOTA YK +', 59, 'Kapolresta Yogyakarta', 'Taman Budaya'),
('vvip', 'FORKOMPIMDA  KOTA YK +', 60, 'Komandan Kodim 0734/Kota Yogyakarta', 'Taman Budaya'),
('vvip', 'FORKOMPIMDA  KOTA YK +', 61, 'Kepala Kejaksaan Negeri Yogyakarta', 'Taman Budaya'),
('vvip', 'FORKOMPIMDA  KOTA YK +', 62, 'Ketua Pengadilan Negeri Yogyakarta', 'Taman Budaya'),
('vvip', 'FORKOMPIMDA  KOTA YK +', 63, 'Sekretaris Daerah Kota Yogyakarta', 'Taman Budaya'),
('vvip', 'FORKOMPIMDA  KOTA YK +', 64, 'Ketua Dharma Wanita Persatuan Kota Yk', 'Taman Budaya'),
('vvip', 'FORKOMPIMDA  KOTA YK +', 65, 'Kepala Dinas Pariwisata Kota Yogyakarta', 'Taman Budaya'),
('vvip', 'Anggota DPRD kota Yogyakarta', 66, 'Eko Djoko Widiyatno, S.H., M.H.', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 67, 'Solihul Hadi, S.H., M.Kn.', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 68, 'Dhian Novitasari, S.Pd.', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 69, 'Krisnadi Setyawan', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 70, 'Ririk Banowati Permanasari, S.H.', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 71, 'Marwoto Hadi, S.H.', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 72, 'Darini, S.IP.', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 73, 'Sigit Nurcahyo, S.H.', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 74, 'Novita Mawar Sharon', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 75, 'Haryanto, S.E.', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 76, 'Ipung Purwandari, S.H.', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 77, 'Agus Riyanto', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 78, 'Endro Sulaksono', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 79, 'Susanto Dwi Antoro, S.E.', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 80, 'H. Danang Rudiyatmoko', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 81, 'R. Candra Akbar Ishmata, S.H.', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 82, 'Muhammad Affan', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 83, 'Yogo Prasetyo Pri Hutomo', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 84, 'Bambang Seno Baskoro, S.T.', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 85, 'Munazar, M.Psi.', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 86, 'Sigit Wicaksono, S.Kom.', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 87, 'Dwi Candra Putra, S.P., M.I.P.', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 88, 'Oleg Yohan', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 89, 'Choliq Nugroho Adji', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 90, 'Cahyo Wibowo, S.T.', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 91, 'Fajar Kurniawan, S.IP.', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 92, 'Mu''adz A. A., S.E., M.E.', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 93, 'Nurcahyo Nugroho', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 94, 'Mohammad Sofyan, S.T.', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 95, 'Tri Waluko Widodo, A.Md.', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 96, 'Affan Baskara Patria, S.IP.', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 97, 'Indaruwanto Eko Cahyono', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 98, 'Agus Trianto', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 99, 'H. Setyaji Hermawan', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 100, 'Taufiq Setiawan, S.Sn.', 'Jalan Sri Wedani'),
('vvip', 'Anggota DPRD kota Yogyakarta', 101, 'I Dewa Putu Adhi Yogana, S.S.', 'Jalan Sri Wedani'),
('vvip', 'UNDANGAN PEJABAT PEMDA DIY', 102, 'Sekretaris Daerah DIY', 'BPD Senopati'),
('vvip', 'UNDANGAN PEJABAT PEMDA DIY', 103, 'Paniradya Pati DIY', 'BPD Senopati'),
('vvip', 'UNDANGAN PEJABAT PEMDA DIY', 104, 'Kepala Dinas Pariwisata D.I.Y', 'BPD Senopati'),
('vvip', 'UNDANGAN PEJABAT PEMDA DIY', 105, 'Kepala Dinas Kebudayaan ( Kundha Kabudayan ) D.I.Y.', 'BPD Senopati'),
('vvip', 'UNDANGAN PEJABAT PEMDA DIY', 106, 'Kepala Dinas Koperasi dan Usaha Kecil Menengah D.I.Y.', 'BPD Senopati'),
('vvip', 'UNDANGAN PEJABAT PEMDA DIY', 107, 'Kepala UPT Pengelolaan Kawasan Sumbu Filosofis', 'BPD Senopati'),
('vvip', 'UNDANGAN PEJABAT PEMKOT YK', 108, 'Asisten Pemerintahan dan Kesejahteraan Rakyat Setda Kota Yogyakarta', 'Jalan Sri Wedani'),
('vvip', 'UNDANGAN PEJABAT PEMKOT YK', 109, 'Asisten Perekonomian dan Pembangunan Setda Kota Yogyakarta', 'Jalan Sri Wedani'),
('vvip', 'UNDANGAN PEJABAT PEMKOT YK', 110, 'Asisten Administrasi Umum Setda Kota Yogyakarta', 'Jalan Sri Wedani'),
('vvip', 'UNDANGAN VVIP LAINNYA', 111, 'Pimpinan PT Angkasa Pura / YIA', 'TKP P.Senopati'),
('vvip', 'UNDANGAN VVIP LAINNYA', 112, 'Kepala Daops VI PT KAI', 'TKP P.Senopati'),
('vvip', 'UNDANGAN VVIP LAINNYA', 113, 'Pimpinan BPD D.I.Yogyakarta', 'TKP P.Senopati'),
('vvip', 'UNDANGAN VVIP LAINNYA', 114, 'Pimpinan BPD D.I.Yogyakarta/Cabang Senopati', 'TKP P.Senopati'),
('vvip', 'UNDANGAN VVIP LAINNYA', 115, 'Pimpinan Wilayah Bank Mandiri', 'TKP P.Senopati'),
('vvip', 'UNDANGAN VVIP LAINNYA', 116, 'Pimpinan BNI Wilayah Yogyakarta', 'TKP P.Senopati'),
('vvip', 'UNDANGAN VVIP LAINNYA', 117, 'Pimpinan BRI Wilayah Yogyakarta', 'TKP P.Senopati'),
('vvip', 'UNDANGAN VVIP LAINNYA', 118, 'Pimpinan Kantor Pos Indonesia', 'TKP P.Senopati'),
('vvip', 'UNDANGAN STAKE HOLDER TERKAIT', 119, 'Kepala Istana Kepresidenan Yogyakarta', 'TKP P.Senopati'),
('vvip', 'UNDANGAN STAKE HOLDER TERKAIT', 120, 'Kepala Museum Kepresidenan R.I. Balai Kirti', 'TKP P.Senopati'),
('vvip', 'UNDANGAN STAKE HOLDER TERKAIT', 121, 'Kepala Museum Benteng Vredeburg', 'TKP P.Senopati'),
('vvip', 'UNDANGAN STAKE HOLDER TERKAIT', 122, 'Kepala Museum Sonobudoyo', 'TKP P.Senopati'),
('vvip', 'UNDANGAN STAKE HOLDER TERKAIT', 123, 'Kepala Taman Budaya Yogyakarta', 'TKP P.Senopati'),
('vvip', 'UNDANGAN STAKE HOLDER TERKAIT', 124, 'Ketua Perhimpunan Hotel Dan Restoran Indonesia DIY (PHRI DIY)', 'TKP P.Senopati'),
('vvip', 'UNDANGAN STAKE HOLDER TERKAIT', 125, 'Ketua ASITA D.I.Yogyakarta', 'TKP P.Senopati'),
('vvip', 'UNDANGAN STAKE HOLDER TERKAIT', 126, 'Ketua Gabungan Industri Pariwisata Indonesia Yogyakarta (GIPI DIY)', 'TKP P.Senopati'),
('vvip', 'UNDANGAN STAKE HOLDER TERKAIT', 127, 'Ketua Kamar Dagang Dan Industri D.I.Yogyakarta ( Kadin D.I.Y )', 'TKP P.Senopati'),
('vvip', 'UNDANGAN STAKE HOLDER TERKAIT', 128, 'Ketua Perhimpunan Usaha Taman Rekreasi Indonesia Yogyakarta (PUTRI DIY)', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 129, 'Gubernur Daerah Khusus Jakarta', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 130, 'Wali Kota Bandung', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 131, 'Bupati Kabupaten Garut', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 132, 'Wali Kota Bogor', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 133, 'Wali Kota Surakarta', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 134, 'Wali Kota Semarang', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 135, 'Wali Kota Magelang', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 136, 'Bupati Kabupaten Kebumen', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 137, 'Bupati Kabupaten Klaten', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 138, 'Wali Kota Malang', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 139, 'Wali Kota Surabaya', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 140, 'Wali Kota Batu', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 141, 'Bupati Kabupaten Ponorogo', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 142, 'Wali Kota Mojokerto', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 143, 'Wali Kota Singkawang', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 144, 'Bupati Kabupaten Barito Timur', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 145, 'Wali Kota Samarinda', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 146, 'Gubernur Kalimantan Timur', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 147, 'Wali Kota Tarakan', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 148, 'Wali Kota Ambon', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 149, 'Bupati Kabupaten Tambrauw', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 150, 'Wali Kota Makassar', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 151, 'Wali Kota Baubau', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 152, 'Wali Kota Bitung', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 153, 'Bupati Kabupaten Padang Pariaman', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 154, 'Wali Kota Pariaman', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 155, 'Wali Kota Medan', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 156, 'Gubernur Sumatera Utara', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 157, 'Bupati Brebes', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 158, 'Kepala Dinas Pariwisata Kota Medan', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 159, 'Kepala Dinas Pariwisata Kota Palembang', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 160, 'Dinas Kebudayaan, Pariwisata, dan Ekonomi Kreatif Provinsi Sumatera Utara', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 161, 'Dinas Pariwisata Dan Ekonomi Kreatif Provinsi DKI Jakarta', 'TKP P.Senopati'),
('vvip', 'UNDANGAN LUAR DAERAH / PENGISI TAMPILAN', 162, 'Dinas Kebudayaan dan Pariwisata Kabupaten Brebes', 'TKP P.Senopati'),
('vvip', 'UNSUR PERGURUAN TINGGI', 163, 'Rektor Universitas Gadjah Mada', 'TKP P.Senopati'),
('vvip', 'UNSUR PERGURUAN TINGGI', 164, 'Rektor Institut Seni Indonesia Yogyakarta', 'TKP P.Senopati'),
('vvip', 'UNSUR PERGURUAN TINGGI', 165, 'Ketua  Ambarrukmo Palace Tourism Academy (AMPTA)', 'TKP P.Senopati'),
('vvip', 'UNSUR PERGURUAN TINGGI', 166, 'Rektor Universitas Kristen Duta Wacana', 'TKP P.Senopati'),
('vvip', 'UNSUR PERGURUAN TINGGI', 167, 'Rektor Universitas Negeri Yogyakarta', 'TKP P.Senopati'),
('vvip', 'UNSUR PERGURUAN TINGGI', 168, 'Rektor Universitas Islam Negeri Sunan Kalijaga Yogyakarta', 'TKP P.Senopati'),
('vvip', 'UNSUR PERGURUAN TINGGI', 169, 'Ketua Sekolah Tinggi Pariwisata Ambarrukmo Yogyakarta (STIPRAM)', 'TKP P.Senopati'),
('vvip', 'UNSUR PERGURUAN TINGGI', 170, 'Rektor Universitas Sarjanawiyata Tamansiswa (UST)', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 171, 'Staf Ahli Menteri Pariwisata Bidang Transformasi Digital dan Inovasi Pariwisata (Masruroh)', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 172, 'Deputi Bidang Pengembangan Penyelenggaraan Kegiatan ( Event ) Kementerian Pariwisata (Vincensius Jemadu)', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 173, 'Deputi Bidang Pengembangan Strategis Ekonomi Kreatif Kementerian Ekonomi Kreatif ( Cecep Rukendi )', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 174, 'Deputi Bidang Pemasaran Kementerian Pariwisata ( Ni Made aAyu Martini)', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 175, 'Ketua Tim kerja Event daerah wilayah jawa Kementerian Pariwisata', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 176, 'Ketua Tim kerja Strategi promosi event daerah Kementerian Pariwisata', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 177, 'Analis kebijakan ahli muda Kementerian Pariwisata', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 178, 'Satya Brahmantya (Assesor Kementerian Pariwisata)', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 179, 'Adiyatama Pariwisata ahli pertama Kementerian Pariwisata', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 180, 'Tim PCO Kementerian Pariwisata', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 181, 'Cadangan', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 182, 'Cadangan', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 183, 'Cadangan', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 184, 'Cadangan', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 185, 'Cadangan', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 186, 'Cadangan', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 187, 'Cadangan', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 188, 'Cadangan', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 189, 'Cadangan', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 190, 'Cadangan', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 191, 'Cadangan', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 192, 'Cadangan', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 193, 'Cadangan', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 194, 'Cadangan', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 195, 'Cadangan', 'TKP P.Senopati'),
('vvip', 'Tambahan Khusus Tim Kementrian ( untuk tempat duduk )', 196, 'Cadangan', 'TKP P.Senopati'),
('vip_opd_mitra', null, 1, 'Staf Ahli Bidang Perekonomian dan Pembangunan Setda Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 2, 'Staf Ahli  Bidang Administrasi Umum Setda Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 3, 'Staf Ahli Bidang Pemerintahan dan Kesejahteraan Rakyat Setda Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 4, 'Kepala Dinas Pendidikan Pemuda dan Olahraga Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 5, 'Kepala Dinas Kesehatan Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 6, 'Kepala Dinas Perhubungan Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 7, 'Kepala Dinas Kependudukan dan Pencatatan Sipil Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 8, 'Kepala Dinas Kebudayaan ( Kundha Kabudayan )Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 9, 'Kepala Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 10, 'Kepala Dinas Perpustakaan dan Kearsipan Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 11, 'Kepala Dinas Pekerjaan Umum Perumahan dan Kawasan Permukiman Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 12, 'Kepala Dinas Komunikasi Informatika Dan Persandian Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 13, 'Kepala Dinas Lingkungan Hidup Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 14, 'Kepala Dinas Pemberdayaan Perempuan Perlindungan Anak Dan Pengendalian Penduduk Keluarga Berencana Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 15, 'Kepala Dinas Sosial Tenaga Kerja Dan Transmigrasi Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 16, 'Kepala Dinas Perindustrian Koperasi dan Usaha Kecil Menengah Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 17, 'Kepala Dinas Perdagangan Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 18, 'Kepala Dinas Pertanian dan Pangan Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 19, 'Kepala Dinas Pertanahan dan Tata Ruang ( Kundha Niti Mandala Sarta Tata Sasana ) Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 20, 'Kepala Dinas Pemadam Kebakaran dan Penyelamatan Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 21, 'Inspektur Inspektorat Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 22, 'Kepala Satuan Polisi Pamong Praja Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 23, 'Sekretariat DPRD Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', null, 24, 'Direktur RSUD Jogja', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'BADAN DI PEMKOT YOGYAKARTA', 25, 'Kepala Badan Perencanaan Pembangunan Daerah Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'BADAN DI PEMKOT YOGYAKARTA', 26, 'Kepala Badan Kesatuan Bangsa dan Politik Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'BADAN DI PEMKOT YOGYAKARTA', 27, 'Kepala Badan Penanggulangan Bencana Daerah Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'BADAN DI PEMKOT YOGYAKARTA', 28, 'Kepala Badan Pengelolaan Keuangan dan Aset Daerah Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'BADAN DI PEMKOT YOGYAKARTA', 29, 'Kepala Badan Kepegawaian dan Pengembangan Sumber Daya Manusia Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'BAGIAN DI SETDA PEMKOT YOGYAKARTA', 30, 'Kepala Bagian Hukum Setda Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'BAGIAN DI SETDA PEMKOT YOGYAKARTA', 31, 'Kepala Bagian Organisasi Setda Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'BAGIAN DI SETDA PEMKOT YOGYAKARTA', 32, 'Kepala Bagian Umum dan Protokol Setda Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'BAGIAN DI SETDA PEMKOT YOGYAKARTA', 33, 'Kepala Bagian Pengadaan Barang dan Jasa Setda Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'BAGIAN DI SETDA PEMKOT YOGYAKARTA', 34, 'Kepala Bagian Tata Pemerintahan Setda Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'BAGIAN DI SETDA PEMKOT YOGYAKARTA', 35, 'Kepala Bagian Administrasi Pembangunan Setda Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'BAGIAN DI SETDA PEMKOT YOGYAKARTA', 36, 'Kepala Bagian Perekonomian dan Kerjasama Setda Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'BAGIAN DI SETDA PEMKOT YOGYAKARTA', 37, 'Kepala Bagian Administrasi dan Keuangan Setda Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'BAGIAN DI SETDA PEMKOT YOGYAKARTA', 38, 'Kepala Bagian Kesejahteraan Rakyat Setda Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'DINAS / OPD LUAR DAERAH', 39, 'Kepala Dinas Pariwisata Kabupaten Kulon Progo', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'DINAS / OPD LUAR DAERAH', 40, 'Kepala Dinas Pariwisata Kabupaten Bantul', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'DINAS / OPD LUAR DAERAH', 41, 'Kepala Dinas Pariwisata Kabupaten Sleman', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'DINAS / OPD LUAR DAERAH', 42, 'Kepala Dinas Pariwisata Kabupaten Gunung Kidul', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'BUMD +', 43, 'Pimpinan PDAM Tirta Marta Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'BUMD +', 44, 'Pimpinan Bank Jogja', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'BUMD +', 45, 'Pimpinan XT square / Jogjatama Visesa', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'KEMANTREN', 46, 'Mantri Pamong Praja Kraton', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'KEMANTREN', 47, 'Mantri Pamong Praja Gondomanan', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'KEMANTREN', 48, 'Mantri Pamong Praja Mantrijeron', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'KEMANTREN', 49, 'Mantri Pamong Praja Jetis', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'KEMANTREN', 50, 'Mantri Pamong Praja Gondokusuman', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'KEMANTREN', 51, 'Mantri Pamong Praja Mergangsan', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'KEMANTREN', 52, 'Mantri Pamong Praja Umbulharjo', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'KEMANTREN', 53, 'Mantri Pamong Praja Gedongtengan', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'KEMANTREN', 54, 'Mantri Pamong Praja Wirobrajan', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'KEMANTREN', 55, 'Mantri Pamong Praja Pakualaman', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'KEMANTREN', 56, 'Mantri Pamong Praja Kotagede', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'KEMANTREN', 57, 'Mantri Pamong Praja Ngampilan', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'KEMANTREN', 58, 'Mantri Pamong Praja Tegalrejo', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'KEMANTREN', 59, 'Mantri Pamong Praja Danurejan', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'KEMANTREN', 60, 'Kapolsek Kraton', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'KEMANTREN', 61, 'Kapolsek Gondomanan', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'KEMANTREN', 62, 'Kapolsek Gedongtengan', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'KEMANTREN', 63, 'Kapolsek Danurejan', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'KEMANTREN', 64, 'Danramil Kraton', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'KEMANTREN', 65, 'Danramil Gondomanan', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'KEMANTREN', 66, 'Danramil Gedongtengan', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'KEMANTREN', 67, 'Danramil Danurejan', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'STAKE HOLDER', 68, 'Ketua Himpunan Pramuwisata Indonesia Kota Yogyakarta ( HPI )', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'STAKE HOLDER', 69, 'Ketua Perkumpulan Penyelenggara Jasa Boga Indonesia Kota Yogyakarta (PPJI )', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'STAKE HOLDER', 70, 'Ketua Badan Promosi Pariwisata Kota Yogyakarta (BP2KY)', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'STAKE HOLDER', 71, 'Ketua Kamar Dagang Dan Industri Kota Yogyakarta ( Kadin Kota Yk )', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'STAKE HOLDER', 72, 'Ketua Forum Komunikasi Kampung Wisata Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'STAKE HOLDER', 73, 'Ketua Forum Komunikasi Kelompok Sadar Wisata Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'STAKE HOLDER', 74, 'GM Hotel Novotel suites Malioboro (Sponsor TPO)', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'STAKE HOLDER', 75, 'GM Hotel Fortuna Suite Malioboro (Sponsor TPO)', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'STAKE HOLDER', 76, 'Direktur Utama RS PKU Muhammadiyah', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'Student Exchange', 77, 'Peserta student exchange dari Luar Negeri', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'Student Exchange', 78, 'Peserta student exchange dari Luar Negeri', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'Student Exchange', 79, 'Peserta student exchange dari Luar Negeri', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'Student Exchange', 80, 'Peserta student exchange dari Luar Negeri', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'Student Exchange', 81, 'Peserta student exchange dari Luar Negeri', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'Student Exchange', 82, 'Peserta student exchange dari Luar Negeri', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'Student Exchange', 83, 'Peserta student exchange dari Luar Negeri', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'Student Exchange', 84, 'Peserta student exchange dari Luar Negeri', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'Student Exchange', 85, 'Peserta student exchange dari Luar Negeri', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'Student Exchange', 86, 'Peserta student exchange dari Luar Negeri', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'Student Exchange', 87, 'Peserta student exchange dari Luar Negeri', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'Student Exchange', 88, 'Peserta student exchange dari Luar Negeri', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'Student Exchange', 89, 'Peserta student exchange dari Luar Negeri', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'Student Exchange', 90, 'Peserta student exchange dari Luar Negeri', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'Student Exchange', 91, 'Peserta student exchange dari Luar Negeri', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'Student Exchange', 92, 'Peserta student exchange dari Luar Negeri', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'Student Exchange', 93, 'Peserta student exchange dari Luar Negeri', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'Student Exchange', 94, 'Peserta student exchange dari Luar Negeri', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'Student Exchange', 95, 'Peserta student exchange dari Luar Negeri', 'Parkir Sorpelem(Selatan RS PKU)'),
('vip_opd_mitra', 'Student Exchange', 96, 'Peserta student exchange dari Luar Negeri', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', null, 1, 'Ketua Forum Anak Kota Yogyakarta ( FAKTA )', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', null, 2, 'Ketua Forum Anak Kota Yogyakarta ( FAKTA )', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', null, 3, 'Ketua Karang Taruna Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', null, 4, 'Ketua Forum Komunikasi Pekerja Sosial Masyarakat Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', null, 5, 'Ketua Persatuan Umat Buddha Indonesia ( Permabudi) / perwakilan umat Buddha Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', null, 6, 'Ketua Pimpinan Majelis Tinggi Agama Khonghucu Indonesia Yogyakarta / perwakilan umat agama Khonghuchu', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', null, 7, 'Ketua Majelis Ulama Indonesia Kota Yogyakarta / perwakilan umat agama Islam Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', null, 8, 'Ketua BAZNAS Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', null, 9, 'Ketua Forum Kerukunan Umat Beragama Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', null, 10, 'Ketua Parasida Hindu Dharma Indonesia (PHDI) Kota Yogyakarta / perwakilan umat agama Hindhu Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', null, 11, 'Ketua Dewan Pimpinan Daerah Majelis Umat Kristen Indonesia (MUKI) Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', null, 12, 'Ketua Perhimpunan Keagamaan Katholik /KEVIKEPAN / perwakilan umat agama Katholik Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', null, 13, 'Ketua KONI Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', null, 14, 'Ketua Dewan Pendidikan Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', null, 15, 'Dewan Kebudayaan Daerah Istimewa Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', null, 16, 'Ketua Dewan Kebudayaan Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', null, 17, 'Ketua BPC HIPMI Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', null, 18, 'Ketua Persatuan Wartawan Indonesia Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', null, 19, 'Ketua Forum Taruna Siaga Bencana ( Tagana ) Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', null, 20, 'Ketua Perkumpulan Pengusaha Malioboro Ahmad Yani (PPMAY)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', null, 21, 'Ketua Komunitas Andong Malioboro', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', null, 22, 'Ketua Komunitas Becak Kayuh Malioboro', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 23, 'Lurah Bausasran (DN)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 24, 'Lurah Tegalpanggung (DN)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 25, 'Lurah Suryatmajan (DN)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 26, 'Lurah Pringgokusuman (GT)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 27, 'Lurah Sosromenduran(GT)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 28, 'Lurah Baciro (GK)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 29, 'Lurah Demangan (GK)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 30, 'Lurah Klitren (GK)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 31, 'Lurah Kotabaru (GK)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 32, 'Lurah Terban (GK)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 33, 'Lurah Ngupasan (GM)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 34, 'Lurah Prawirodirjan (GM)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 35, 'Lurah Bumijo (JT)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 36, 'Lurah Cokrodiningratan (JT)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 37, 'Lurah Gowongan (JT)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 38, 'Lurah Prenggan (KG)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 39, 'Lurah Purbayan (KG)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 40, 'Lurah Rejowinangun (KG)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 41, 'Lurah Panembahan (KT)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 42, 'Lurah Kadipaten (KT)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 43, 'Lurah Patehan (KT)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 44, 'Lurah Gedongkiwo (MJ)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 45, 'Lurah Suryodingratan (MJ)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 46, 'Lurah Mantrijeron (MJ)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 47, 'Lurah Brontokusuman (MG)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 48, 'Lurah Keparakan (MG)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 49, 'Lurah Wirogunan (MG)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 50, 'Lurah Ngampilan (NG)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 51, 'Lurah Notoprajan (NG)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 52, 'Lurah Gunungketur (PA)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 53, 'Lurah Purwokinanti (PA)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 54, 'Lurah Pandeyan (UH)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 55, 'Lurah Sorosutan (UH)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 56, 'Lurah Giwangan (UH)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 57, 'Lurah Warungboto (UH)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 58, 'Lurah Mujamuju (UH)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 59, 'Lurah Semaki (UH)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 60, 'Lurah Tahunan (UH)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 61, 'Lurah Pakuncen (WB)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 62, 'Lurah Patangpuluhan (WB)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 63, 'Lurah Wirobrajan (WB)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 64, 'Lurah Bener (TR)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 65, 'Lurah Karangwaru (TR)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 66, 'Lurah Kricak (TR)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'LURAH', 67, 'Lurah Tegalrejo (TR)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 68, 'Pinituwo Tuwanggono Bausasran (DN)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 69, 'Pinituwo Tuwanggono Tegalpanggung (DN)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 70, 'Pinituwo Tuwanggono Suryatmajan (DN)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 71, 'Pinituwo Tuwanggono Pringgokusuman (GT)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 72, 'Pinituwo Tuwanggono Sosromenduran(GT)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 73, 'Pinituwo Tuwanggono Baciro (GK)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 74, 'Pinituwo Tuwanggono Demangan (GK)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 75, 'Pinituwo Tuwanggono Klitren (GK)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 76, 'Pinituwo Tuwanggono Kotabaru (GK)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 77, 'Pinituwo Tuwanggono Terban (GK)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 78, 'Pinituwo Tuwanggono Ngupasan (GM)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 79, 'Pinituwo Tuwanggono Prawirodirjan (GM)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 80, 'Pinituwo Tuwanggono Bumijo (JT)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 81, 'Pinituwo Tuwanggono Cokrodiningratan (JT)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 82, 'Pinituwo Tuwanggono Gowongan (JT)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 83, 'Pinituwo Tuwanggono Prenggan (KG)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 84, 'Pinituwo Tuwanggono Purbayan (KG)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 85, 'Pinituwo Tuwanggono Rejowinangun (KG)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 86, 'Pinituwo Tuwanggono Panembahan (KT)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 87, 'Pinituwo Tuwanggono Kadipaten (KT)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 88, 'Pinituwo Tuwanggono Patehan (KT)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 89, 'Pinituwo Tuwanggono Gedongkiwo (MJ)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 90, 'Pinituwo Tuwanggono Suryodingratan (MJ)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 91, 'Pinituwo Tuwanggono Mantrijeron (MJ)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 92, 'Pinituwo Tuwanggono Brontokusuman (MG)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 93, 'Pinituwo Tuwanggono Keparakan (MG)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 94, 'Pinituwo Tuwanggono Wirogunan (MG)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 95, 'Pinituwo Tuwanggono Ngampilan (NG)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 96, 'Pinituwo Tuwanggono Notoprajan (NG)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 97, 'Pinituwo Tuwanggono Gunungketur (PA)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 98, 'Pinituwo Tuwanggono Purwokinanti (PA)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 99, 'Pinituwo Tuwanggono Pandeyan (UH)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 100, 'Pinituwo Tuwanggono Sorosutan (UH)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 101, 'Pinituwo Tuwanggono Giwangan (UH)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 102, 'Pinituwo Tuwanggono Warungboto (UH)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 103, 'Pinituwo Tuwanggono Mujamuju (UH)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 104, 'Pinituwo Tuwanggono Semaki (UH)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 105, 'Pinituwo Tuwanggono Tahunan (UH)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 106, 'Pinituwo Tuwanggono Pakuncen (WB)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 107, 'Pinituwo Tuwanggono Patangpuluhan (WB)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 108, 'Pinituwo Tuwanggono Wirobrajan (WB)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 109, 'Pinituwo Tuwanggono Bener (TR)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 110, 'Pinituwo Tuwanggono Karangwaru (TR)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 111, 'Pinituwo Tuwanggono Kricak (TR)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'TUWANGGONO', 112, 'Pinituwo Tuwanggono Tegalrejo (TR)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN MEDIA', 113, 'Pimpinan Harian Kedaulatan Rakyat', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN MEDIA', 114, 'Pimpinan Harian KOMPAS', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN MEDIA', 115, 'Pimpinan Harian Bernas', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN MEDIA', 116, 'Pimpinan Harian Jogja', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN MEDIA', 117, 'Pimpinan Harian Radar Jogja', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN MEDIA', 118, 'Pimpinan Harian Tribune Jogja', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN MEDIA', 119, 'Pimpinan Stasiun TVRI Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN MEDIA', 120, 'Pimpinan Jogja TV', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN MEDIA', 121, 'Pimpinan AdiTV', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN MEDIA', 122, 'Pimpinan TATV Jogja/Sangaji TV', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN MEDIA', 123, 'Pimpinan RBTV', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN LAINNYA', 124, 'Muhammad Arief Budiman (Ketua Komite Ekonomi Kreatif Kota Yogyakarta)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN LAINNYA', 125, 'Anggota Komite Ekonomi Kreatif Kota Yogyakarta)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN LAINNYA', 126, 'Anggota Komite Ekonomi Kreatif Kota Yogyakarta)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN LAINNYA', 127, 'Anggota Komite Ekonomi Kreatif Kota Yogyakarta)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN LAINNYA', 128, 'Anggota Komite Ekonomi Kreatif Kota Yogyakarta)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN LAINNYA', 129, 'Anggota Komite Ekonomi Kreatif Kota Yogyakarta)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN LAINNYA', 130, 'Anggota Komite Ekonomi Kreatif Kota Yogyakarta)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN LAINNYA', 131, 'Anggota Komite Ekonomi Kreatif Kota Yogyakarta)', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN LAINNYA', 132, 'Ketua TIM 9 Badan Penelitian dan Pengembangan Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN LAINNYA', 133, 'Anggota TIM 9 Badan Penelitian dan Pengembangan Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN LAINNYA', 134, 'Anggota TIM 9 Badan Penelitian dan Pengembangan Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN LAINNYA', 135, 'Anggota TIM 9 Badan Penelitian dan Pengembangan Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN LAINNYA', 136, 'Anggota TIM 9 Badan Penelitian dan Pengembangan Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN LAINNYA', 137, 'Anggota TIM 9 Badan Penelitian dan Pengembangan Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN LAINNYA', 138, 'Anggota TIM 9 Badan Penelitian dan Pengembangan Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN LAINNYA', 139, 'Anggota TIM 9 Badan Penelitian dan Pengembangan Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN LAINNYA', 140, 'Anggota TIM 9 Badan Penelitian dan Pengembangan Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN LAINNYA', 141, 'Anggota TIM 9 Badan Penelitian dan Pengembangan Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN LAINNYA', 142, 'Ketua FORPI Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN LAINNYA', 143, 'Anggota FORPI Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('wilayah_ormas', 'UNDANGAN LAINNYA', 144, 'Anggota FORPI Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('lansia_disabilitas_anak', null, 1, 'Ketua Forkom Lansia Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('lansia_disabilitas_anak', null, 2, 'Pengurus Forkom Lansia Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('lansia_disabilitas_anak', null, 3, 'Pengurus Forkom Lansia Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('lansia_disabilitas_anak', null, 4, 'Pengurus Forkom Lansia Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('lansia_disabilitas_anak', null, 5, 'Perwakilan Anggota Lansia Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('lansia_disabilitas_anak', null, 6, 'Perwakilan Anggota Lansia Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('lansia_disabilitas_anak', null, 7, 'Perwakilan Anggota Lansia Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('lansia_disabilitas_anak', 'Disabilitas Kota Yogyakarta', 8, 'Pengurus Forum Disabilitas Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('lansia_disabilitas_anak', 'Disabilitas Kota Yogyakarta', 9, 'Pengurus Forum Disabilitas Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('lansia_disabilitas_anak', 'Disabilitas Kota Yogyakarta', 10, 'Pendamping Disabilitas Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('lansia_disabilitas_anak', 'Disabilitas Kota Yogyakarta', 11, 'Pendamping Disabilitas Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('lansia_disabilitas_anak', 'Disabilitas Kota Yogyakarta', 12, 'Pendamping Disabilitas Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('lansia_disabilitas_anak', 'Disabilitas Kota Yogyakarta', 13, 'Perwakilan Disabilitas Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('lansia_disabilitas_anak', 'Disabilitas Kota Yogyakarta', 14, 'Perwakilan Disabilitas Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('lansia_disabilitas_anak', 'Disabilitas Kota Yogyakarta', 15, 'Perwakilan Disabilitas Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('lansia_disabilitas_anak', 'Disabilitas Kota Yogyakarta', 16, 'Perwakilan Disabilitas Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('lansia_disabilitas_anak', 'Forum Anak Kota Yogyakarta', 17, 'Pendamping Forum Anak Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('lansia_disabilitas_anak', 'Forum Anak Kota Yogyakarta', 18, 'Perwakilan Forum Anak Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('lansia_disabilitas_anak', 'Forum Anak Kota Yogyakarta', 19, 'Perwakilan Forum Anak Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)'),
('lansia_disabilitas_anak', 'Forum Anak Kota Yogyakarta', 20, 'Perwakilan Forum Anak Kota Yogyakarta', 'Parkir Sorpelem(Selatan RS PKU)');
